# Generated by Django 2.2.3 on 2019-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190919_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AlterField(
            model_name='question',
            name='answers1',
            field=models.ManyToManyField(related_name='question_answer', to='core.Answer', verbose_name='Ответы1'),
        ),
    ]
