# Generated by Django 2.2.3 on 2019-09-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190923_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.CharField(blank=True, max_length=30303, verbose_name='Ответы'),
        ),
    ]
