# Generated by Django 2.2.3 on 2019-09-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='question_answer', to='core.Answer', verbose_name='Ответы1'),
        ),
    ]
