# Generated by Django 2.2.3 on 2019-09-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190927_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
