# Generated by Django 2.2.3 on 2019-09-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ravchon_auth', '0001_initial'),
        ('core', '0011_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='core.Answer', verbose_name='Ответы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question', verbose_name='Вопрос')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravchon_auth.Profile', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='core.StudentAnswer', verbose_name='Вопросы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravchon_auth.Profile', verbose_name='Пользователь')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Test', verbose_name='Тест')),
            ],
        ),
    ]
