# Generated by Django 2.2.3 on 2019-09-27 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentanswer_studenttest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Ответы студентов'},
        ),
        migrations.AlterModelOptions(
            name='studenttest',
            options={'verbose_name': 'Тест студента', 'verbose_name_plural': 'Тесты студентов'},
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='question_answer', to='core.Answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
