# Generated by Django 2.2.3 on 2019-09-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190927_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=150, verbose_name='Название теста'),
        ),
    ]
