# Generated by Django 2.2.3 on 2019-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190927_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='pov',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='shel',
            field=models.FloatField(default=0),
        ),
    ]
