# Generated by Django 2.2.3 on 2019-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191003_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
