# Generated by Django 2.2.3 on 2019-10-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_studenttest_passed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttest',
            old_name='passed',
            new_name='done',
        ),
    ]
