# Generated by Django 2.2.3 on 2019-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191005_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttest',
            name='done',
        ),
        migrations.AddField(
            model_name='studenttest',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
