# Generated by Django 2.2.6 on 2019-10-04 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_m_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M',
            new_name='Test',
        ),
    ]
