# Generated by Django 2.2.3 on 2019-10-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20191004_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
